# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.cache/wt [current_project]
set_property parent.project_path D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/data_sync.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/UART_tx_control_esclavo.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/TX_seq.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/decoder_7_seg.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/contador_hexa.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/uart_tx.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/uart_rx.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/uart_baud_tick_gen.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/unsigned_to_bcd.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/UART_tx_control_wrapper.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/UART_RX_CTRL.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/uart_basic.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/treintaydos_to_siete.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/modulo_alu1.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/clk_divider.v
  D:/Universidad/LAB_DIGITALES/Examples/ELO212-example-modules-master/uart_esclavo/uart_esclavo.srcs/sources_1/new/esclavo_endpoint_uart.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Sebastián/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Sebastián/Downloads/Nexys4DDR_Master.xdc]


synth_design -top esclavo_endpoint_uart -part xc7a100tcsg324-1


write_checkpoint -force -noxdef esclavo_endpoint_uart.dcp

catch { report_utilization -file esclavo_endpoint_uart_utilization_synth.rpt -pb esclavo_endpoint_uart_utilization_synth.pb }
